baseurl:
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
encoding: utf-8
markdown: kramdown
kramdown:
input: GFM
description: 年华老去，终成朽枯。
domain: 
avatar: assets\img\pictures\sculpture.jpg

